[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[executable]]
name = "demo_app"
source-dir = "app"
main = "main.f90"

[[test]]
name = "test_demo"
source-dir = "test"
main = "test_demo.f90"

[dependencies]
# No external dependencies for this basic example