name: E2E Coverage Validation

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-coverage:
    name: Compare FortCov vs Cobertura (gcovr)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gfortran and Python tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran python3 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install gcovr

      - name: Set up fpm
        uses: fortran-lang/setup-fpm@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: v0.10.1

      - name: Build tests with coverage and generate reports
        run: |
          # Build and run tests with coverage flags
          fpm test --flag "-fprofile-arcs -ftest-coverage"
          # Generate Cobertura XML via gcovr (align file set with FortCov defaults)
          gcovr -r . \
            --exclude 'build/.*' \
            --exclude 'test/.*' \
            --xml-pretty -o coverage.xml \
            || gcovr --exclude 'build/.*' --exclude 'test/.*' --xml-pretty -o coverage.xml
          # Generate FortCov markdown (single command workflow)
          fpm build --profile release
          FORTCOV_BIN=$(find build -type f -path '*/app/fortcov' | head -n1)
          if [ -z "${FORTCOV_BIN}" ]; then
            echo "FortCov binary not found in build tree" >&2
            exit 2
          fi
          # Ensure FortCov uses real gcov instead of synthesized .gcov files
          export FORTCOV_USE_REAL_GCOV=1
          # Enable auto-gcov generation to produce .gcov files in CI
          "${FORTCOV_BIN}" --gcov --output=coverage.md

      - name: Compare totals (Cobertura vs FortCov)
        run: |
          python3 scripts/compare_coverage_metrics.py coverage.xml coverage.md

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-coverage-artifacts
          path: |
            coverage.xml
            coverage.md
